export default {
  FETCH_ARTICLES_IDS_START: 'FETCH_ARTICLES_IDS_START',
  FETCH_ARTICLES_IDS_SUCCESS: 'FETCH_ARTICLES_IDS_SUCCESS',
  FETCH_ARTICLES_IDS_ERROR: 'FETCH_ARTICLES_IDS_ERROR',

  FETCH_ARTICLES_START: 'FETCH_ARTICLES_START',
  FETCH_ARTICLES_SUCCESS: 'FETCH_ARTICLES_SUCCESS',
  FETCH_ARTICLES_ERROR: 'FETCH_ARTICLES_ERROR',

  FETCH_ARTICLE_SUCCESS: 'FETCH_ARTICLE_SUCCESS',
  FETCH_ARTICLE_ERROR: 'FETCH_ARTICLE_ERROR'
}
